name: .NET Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    #runs-on: windows-2019
    runs-on: self-hosted
    
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2 #working 
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build solution
      run: msbuild DemoApp.sln /p:Configuration=Release

        
