name: .NET Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    #runs-on: windows-2019
    runs-on: self-hosted
    
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2 #working 
      
    - name: Set up .NET Framework 4.0
      uses: microsoft/setup-msbuild@v1.0.3
      with:
          msbuild-version: '16.0' # Make sure the MSBuild version supports .NET 4.0

    - name: Build solution
      run: msbuild DemoApp.sln /p:Configuration=Release

        
